### PR TITLE
Fix stuttering when starting audio

### PR DESCRIPTION
**Pull request by rudcode**
Make a while loop to send all buffer instead of dropping it

### CODE REVIEW

**Comment by silverchris** [comment]
Just getting back into working on this project now. Will do some testing and hopefully merging of your fixes soon.
I also wanted to thank you for your contributions!

**Comment by rudcode** [comment]
Really nice to hear that! Thank you for this project too.

Have you test this commit?

**Comment by YouHusam** [comment]
I tested this, AA kept hanging when navigation/notification sound was supposed to be playing if music was playing. I had to restart my head unit 4 times at least in a 20 minutes drive, then I stopped using it for the rest of the day.

**Comment by silverchris** [comment]
Doing some testing, and I think the stutter is mostly caused by the limited speed of the WiFi connection. Did a bunch of tweaking today, and noticed that it would drop when there was a lot of video updates. 
Tried it over USB and no issues... Going to continue looking into this

**Comment by rudcode** [comment]
@YouHusam Thank you for testing it. My bad I didn't test it with music playing in the background.

@silverchris  Just seeing the master branch now. I think this isn't relevant anymore, and will test the master branch soon, thank you 👍

**Pull request closed without merging**
